import type { Teardown } from "./types";

/** Render a teardown as a portable markdown briefing. */
export function teardownToMarkdown(
  report: Teardown,
  meta: {
    url: string;
    generatedAt: number;
    durationMs?: number;
    provider?: string;
    model?: string;
  },
): string {
  const lines: string[] = [];
  const date = new Date(meta.generatedAt).toISOString().slice(0, 10);

  lines.push(`# ${report.company} — competitive teardown`);
  lines.push("");
  lines.push(`> ${report.headline}`);
  lines.push("");
  lines.push(`**Source:** ${meta.url}  `);
  lines.push(`**Generated:** ${date}  `);
  lines.push(`**Confidence:** ${report.confidence}`);
  if (meta.provider) {
    const model = meta.model ? ` / ${meta.model}` : "";
    lines.push(`  \n**Synthesised by:** ${meta.provider}${model}`);
  }
  if (meta.durationMs) {
    lines.push(`  \n**Run time:** ${(meta.durationMs / 1000).toFixed(1)}s`);
  }
  lines.push("");

  lines.push("## Positioning");
  lines.push("");
  lines.push(report.positioning.summary);
  lines.push("");
  lines.push(`**Target customer:** ${report.positioning.targetCustomer}`);
  lines.push("");
  if (report.positioning.valueProps.length) {
    lines.push("**Value props**");
    lines.push("");
    report.positioning.valueProps.forEach((v) => lines.push(`- ${v}`));
    lines.push("");
  }
  if (report.positioning.differentiators.length) {
    lines.push("**Claimed differentiators**");
    lines.push("");
    report.positioning.differentiators.forEach((v) => lines.push(`- ${v}`));
    lines.push("");
  }

  lines.push("## Pricing");
  lines.push("");
  lines.push(report.pricing.summary);
  lines.push("");
  lines.push(`**Model:** ${report.pricing.model}  `);
  lines.push(`**Free tier:** ${report.pricing.freeTier}`);
  lines.push("");
  if (report.pricing.tiers.length) {
    lines.push("| Tier | Price | Notes |");
    lines.push("| --- | --- | --- |");
    report.pricing.tiers.forEach((t) =>
      lines.push(`| ${esc(t.name)} | ${esc(t.price)} | ${esc(t.notes)} |`),
    );
    lines.push("");
  }

  lines.push("## Tech stack signals");
  lines.push("");
  lines.push(report.techStack.summary);
  lines.push("");
  report.techStack.signals.forEach((s) =>
    lines.push(`- **${s.name}** _(${s.category})_ — ${s.evidence}`),
  );
  lines.push("");

  lines.push("## What users complain about");
  lines.push("");
  lines.push(report.complaints.summary);
  lines.push("");
  report.complaints.items.forEach((c) =>
    lines.push(`- **[${c.severity}]** ${c.complaint} _(${c.source})_`),
  );
  lines.push("");

  lines.push("## Recent moves");
  lines.push("");
  lines.push(report.recentMoves.summary);
  lines.push("");
  report.recentMoves.items.forEach((m) =>
    lines.push(`- **${m.when}** — ${m.move} _(${m.source})_`),
  );
  lines.push("");

  lines.push("## Opportunities");
  lines.push("");
  lines.push(report.opportunities.summary);
  lines.push("");
  report.opportunities.items.forEach((o, i) => {
    lines.push(`### ${i + 1}. ${o.gap}`);
    lines.push("");
    lines.push(`**Why it's open:** ${o.why}`);
    lines.push("");
    lines.push(`**How to exploit:** ${o.howToExploit}`);
    lines.push("");
  });

  if (report.gaps.length) {
    lines.push("## What this run could not establish");
    lines.push("");
    report.gaps.forEach((g) => lines.push(`- ${g}`));
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("_Generated by the Competitive Intelligence Agent (Solari + Claude)._");

  return lines.join("\n");
}

function esc(value: string): string {
  return value.replace(/\|/g, "\\|");
}

export function slugify(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "teardown"
  );
}
